apiVersion: v1
kind: Pod
metadata:
  name: wasmedge-test
  annotations:
    run.oci.handler: wasmedge
spec:
  runtimeClassName: wasmedge
  containers:
  - name: wasm-container
    image: wasmedge/example-wasi:latest
  restartPolicy: Never
